INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (2, 'doc_add', 'Docket Add', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (1, 'doc_view', 'Docket View', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (3, 'doc_edit', 'Docket Edit', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (4, 'doc_admin', 'Docket Admin', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (5, 'doc_query', 'Docket Query', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (6, 'doc_delete', 'Docket Delete', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (7, 'fin_view', 'Finance View', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (8, 'fin_add', 'Finance Add', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (9, 'fin_edit', 'Finance Edit', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (10, 'fin_admin', 'Finance Admin', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (11, 'fin_query', 'Finance Query', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (12, 'fin_delete', 'Finance Delete', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (13, 'fin_approve', 'Finance Approver', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (14, 'user_view', 'View Users', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (15, 'user_add', 'Add Users', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (16, 'user_edit', 'Edit Users', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (17, 'user_admin', 'Administrate Users', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (18, 'user_query', 'Query Users', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (19, 'user_delete', 'Delete Users', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (20, 'dev_edit', 'Develop Edit', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (21, 'dev_read', 'Read Dev Logs 1', null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (22, 'send_mail', 'Send Emails', 1 null, null);
INSERT INTO management.perm_types (seq, perm_desc, name_short, grantable, added_by, updated_by) VALUES (23, 'guest', 'Guest', 0 null, null);
